FROM alpine:3.18@sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc851978 as otelc_curl
RUN apk --update add curl

FROM otel/opentelemetry-collector:latest@sha256:11cb391eff16542f6fef93be9536454dc5c38552c0285a349f81539e8b7caf85

COPY --from=otelc_curl / /

COPY ./otel-collector-config.yaml /etc/otel-collector-config.yaml
USER 0
RUN chmod o+r /etc/otel-collector-config.yaml
USER nobody
