name: check-pr-description
on:
  pull_request:
    types: ['opened', 'edited', 'reopened']

jobs:
  check-pr-description:
    name: Check PR Description
    runs-on: ubuntu-latest
    if: github.repository_owner == 'envoyproxy'


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./.github/actions/check-pr-description/requirements.txt
    - name: Check Description
      run: python ./.github/actions/check-pr-description/check_pr_description.py
      env:
        GITHUB_PR_ID: ${{ github.event.pull_request.number }}
